title: West Spring Secondary School - Official School Website
url: https://www.westspringsec.moe.edu.sg
favicon: /images/WEST SPRING SEC - HiRes Sch Crest.jpg
colors:
  primary-color: "#f8e71c"
  secondary-color: "#26359e"
  media-colors:
    - title: media-color-one
      color: "#f57823"
    - title: media-color-two
      color: "#f56d23"
    - title: media-color-three
      color: "#f58323"
    - title: media-color-four
      color: "#f57e23"
    - title: media-color-five
      color: "#f57823"
description: Official school website of West Spring Secondary School
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://moe-westspringsec-staging.netlify.app
prod: https://moe-westspringsec-prod.netlify.app
resources_name: resource
shareicon: /images/WEST SPRING SEC - HiRes Sch Crest.jpg
is_government: true
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
